### ISSUE TITLE
Joined conversation doesn't reflect the coBrowsing status?

### ISSUE THREAD

**Issue by nashfive** [unblu/ios-sdk-xcframeworks#5]
@indaos 
When using a PIN to join a conversation, the Conversation object returned by the `joinConversation(pin: pin, onComplete:)` doesn't provide a way to differentiate between an agent-initiated "Join" or "Join mobile" conversation. 
In both scenario, the `conversation.isMobileCoBrowsingActive` is set to `false`. 

This means for example that, when the user terminates the co-browsing session, we can't know if we should re-open the Unblu view to let him resume the discussion in a joined conversation (not a "join mobile" conversation).

Any idea on how we can fix this?

**Comment by truebden** [comment]
hey @nashfive,
yes your observation is correct that the `joinConversation` with a pin doesn't know/care about what kind of converstation is joined. What you may would need is the initial engagement type of the converstation on the returned conversation object. That would be a valid feature request. Could you create a feature request for that via the normal support? (not sure if you have contact to a project leader/sales person from Unblu?)

About the flag `conversation.isMobileCoBrowsingActive`. This should be `true` as long as mobile co-browsing is actively running independend of the initial starting type. So that flag would not help you in your case. But it would be weird if it is always `false` even if mobile co-browsing is currently active. If that is true, this would be a bug.

**Comment by nashfive** [comment]
Hi @truebden 
Thanks for your feedback! I suspected that we didn't a way to evaluate the context of a co-browsing session. And as for the `isMobileCoBrowsingActive` property, I think it's working as expected. I was testing it before and after the co-browsing session...
I will check with my project manager and he will determine with our client if we need to open a feature request.

**Comment by truebden** [comment]
thank you!
